name = "resona-backend"
main = "src/index.js"
compatibility_date = "2024-01-01"

[env.production]
name = "resona-backend-prod"

[env.staging]
name = "resona-backend-staging"

[[d1_databases]]
binding = "DB"
database_name = "resona-db"
database_id = "your-database-id-here"

[[kv_namespaces]]
binding = "EMOTION_POOL"
id = "your-kv-namespace-id-here"

[vars]
ENVIRONMENT = "development"
MAX_SUBMISSIONS_PER_MINUTE = "3"
MAX_COLLECTIONS_PER_USER = "20"
EMOTION_TAGS = "sad,lonely,happy,confused,relieved,angry,missing,yearning"
OPENAI_API_URL = "https://new-api-latest-m4mh.onrender.com/v1"
GEMINI_API_URL = "https://generativelanguage.googleapis.com/v1beta"
OPENAI_MODEL = "gpt-3.5-turbo"
GEMINI_MODEL = "gemini-pro"
OPENAI_API_KEY=""
