name = "resona-backend"
main = "src/index.js"
compatibility_date = "2024-01-01"

[env.production]
name = "resona-backend-prod"

[env.staging]
name = "resona-backend-staging"

[[d1_databases]]
binding = "DB"
database_name = "resona-db"
database_id = "69b75a31-d875-431f-b978-fed0b4645fc4"

[[kv_namespaces]]
binding = "EMOTION_POOL"
id = "b0a7141c2e6a43b6abc2fd7bc0c320d2"

[vars]
ENVIRONMENT = "development"
MAX_SUBMISSIONS_PER_MINUTE = "3"
MAX_COLLECTIONS_PER_USER = "20"
OPENAI_API_URL = "https://new-api-latest-m4mh.onrender.com/v1"
GEMINI_API_URL = "https://generativelanguage.googleapis.com/v1beta"
OPENAI_MODEL = "gpt-3.5-turbo-0613"
GEMINI_MODEL = "gemini-pro"
OPENAI_API_KEY=""
